function PlanPreview({
  plan,
  generatedBy,
  fallbackReason,
  constraints,
  onConstraintChange,
  onSessionProfileChange,
  onApply,
  onRegenerate,
  onRollback,
  canRollback,
  loading,
}) {
  if (!plan) {
    return (
      <section className="ai-plan-preview">
        <h3>Plan Preview</h3>
        <p className="ai-muted">Generate a plan to preview sessions and settings.</p>
      </section>
    );
  }

  return (
    <section className="ai-plan-preview">
      <div className="ai-plan-header">
        <h3>{plan.planTitle}</h3>
        <span className="badge">{plan.horizonDays} days</span>
      </div>

      <p className="ai-muted">Generated by: {generatedBy}</p>
      {fallbackReason && <p className="ai-warning">Fallback used: {fallbackReason}</p>}
      <p className="ai-rationale"><strong>Why this plan:</strong> {plan.rationale}</p>
      <p className="ai-rationale"><strong>Confidence:</strong> {(plan.confidence * 100).toFixed(0)}%</p>

      <div className="ai-grid">
        <label>
          Focus (min)
          <input
            type="number"
            min="1"
            max="120"
            value={plan.sessionProfile.defaultFocusMinutes}
            onChange={(event) => onSessionProfileChange('defaultFocusMinutes', Number(event.target.value))}
          />
        </label>
        <label>
          Break (min)
          <input
            type="number"
            min="1"
            max="60"
            value={plan.sessionProfile.defaultBreakMinutes}
            onChange={(event) => onSessionProfileChange('defaultBreakMinutes', Number(event.target.value))}
          />
        </label>
        <label>
          Long Break (min)
          <input
            type="number"
            min="5"
            max="60"
            value={plan.sessionProfile.longBreakMinutes}
            onChange={(event) => onSessionProfileChange('longBreakMinutes', Number(event.target.value))}
          />
        </label>
        <label>
          Sessions before Long Break
          <input
            type="number"
            min="1"
            max="8"
            value={plan.sessionProfile.sessionsBeforeLongBreak}
            onChange={(event) => onSessionProfileChange('sessionsBeforeLongBreak', Number(event.target.value))}
          />
        </label>
      </div>

      <div className="ai-constraints">
        <h4>Locked Constraints</h4>
        <label className="ai-checkbox">
          <input
            type="checkbox"
            checked={Boolean(constraints.noLateNightSessions)}
            onChange={(event) => onConstraintChange('noLateNightSessions', event.target.checked)}
          />
          No late-night sessions
        </label>
        <label className="ai-checkbox">
          <input
            type="checkbox"
            checked={constraints.gamesEnabled !== false}
            onChange={(event) => onConstraintChange('gamesEnabled', event.target.checked)}
          />
          Allow game breaks
        </label>
        <label>
          Max focus minutes
          <input
            type="number"
            min="1"
            max="120"
            value={constraints.maxFocusMinutes}
            onChange={(event) => onConstraintChange('maxFocusMinutes', Number(event.target.value) || 25)}
          />
        </label>
      </div>

      <div className="ai-daily-plans">
        {plan.dailyPlans.map((day) => (
          <article key={day.date} className="ai-day-card">
            <h4>{day.date}</h4>
            <ul>
              {day.sessions.map((session, index) => (
                <li key={`${day.date}-${session.subject}-${index}`}>
                  <strong>{session.subject}</strong> — {session.topic} ({session.focusMinutes}m/{session.breakMinutes}m)
                </li>
              ))}
            </ul>
            <p>{day.notes}</p>
          </article>
        ))}
      </div>

      <h4>Adaptation Rules</h4>
      <ul className="ai-adaptation-list">
        {plan.adaptationRules.map((rule, index) => (
          <li key={`${rule.condition}-${index}`}>
            <strong>{rule.condition}</strong>
            <span>{rule.adjustment}</span>
          </li>
        ))}
      </ul>

      <div className="ai-actions">
        <button className="btn btn-primary" type="button" onClick={onApply} disabled={loading || !plan.needsUserConfirmation}>
          Apply Plan
        </button>
        <button className="btn btn-secondary" type="button" onClick={onRegenerate} disabled={loading}>
          Regenerate
        </button>
        <button className="btn btn-outline" type="button" onClick={onRollback} disabled={loading || !canRollback}>
          Rollback
        </button>
      </div>
    </section>
  );
}

export default PlanPreview;
